package south2md

import (
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/samber/lo"
)

const netscapeCookieHeader = "# Netscape HTTP Cookie File"
const httpOnlyPrefix = "#HttpOnly_"

// CookieManager Cookie管理器
type CookieManager struct {
	jar *CookieJar
}

// NewCookieManager 创建新的Cookie管理器
func NewCookieManager() *CookieManager {
	return &CookieManager{
		jar: &CookieJar{
			Cookies:     make([]CookieEntry, 0),
			LastUpdated: time.Now(),
		},
	}
}

// LoadFromFile 从文件加载Cookie
func (cm *CookieManager) LoadFromFile(filepath string) error {
	if filepath == "" {
		return nil
	}

	data, err := os.ReadFile(filepath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read cookie file failed: %v", err)
	}

	if len(data) == 0 {
		// 空文件，使用默认值
		return nil
	}

	cm.jar.Cookies = make([]CookieEntry, 0)
	lines := strings.Split(string(data), "\n")
	for _, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		if line == "" {
			continue
		}

		httpOnly := false
		if strings.HasPrefix(line, httpOnlyPrefix) {
			httpOnly = true
			line = strings.TrimPrefix(line, httpOnlyPrefix)
		} else if strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Split(line, "\t")
		if len(parts) < 7 {
			parts = strings.Fields(line)
		}
		if len(parts) < 7 {
			continue
		}

		if len(parts) > 7 {
			parts = append(parts[:6], strings.Join(parts[6:], "\t"))
		}

		domain := parts[0]
		includeSubdomains := strings.EqualFold(parts[1], "TRUE")
		path := parts[2]
		secure := strings.EqualFold(parts[3], "TRUE")
		expiry := parts[4]
		name := parts[5]
		value := parts[6]

		if includeSubdomains && domain != "" && !strings.HasPrefix(domain, ".") {
			domain = "." + domain
		}
		if !includeSubdomains && strings.HasPrefix(domain, ".") {
			domain = strings.TrimPrefix(domain, ".")
		}

		var expires time.Time
		if expiry != "" {
			if ts, err := strconv.ParseInt(expiry, 10, 64); err == nil && ts > 0 {
				expires = time.Unix(ts, 0)
			}
		}

		cm.AddCookie(&CookieEntry{
			Name:     name,
			Value:    value,
			Domain:   domain,
			Path:     path,
			Expires:  expires,
			Secure:   secure,
			HttpOnly: httpOnly,
		})
	}

	// 清理过期Cookie
	cm.CleanExpired()

	if !lo.ContainsBy(cm.jar.Cookies, func(item CookieEntry) bool {
		return item.Name == "eb9e6_winduser"
	}) {
		slog.Warn("User not logged in, clearing cookies")
		cm.ClearCookies()
	}

	return nil
}

// SaveToFile 保存Cookie到文件
func (cm *CookieManager) SaveToFile(filepath string) error {
	if filepath == "" {
		return nil
	}

	cm.jar.LastUpdated = time.Now()

	// 清理过期Cookie
	cm.CleanExpired()

	var builder strings.Builder
	builder.WriteString(netscapeCookieHeader)
	builder.WriteString("\n")
	builder.WriteString("# This file was generated by south2md. Edit at your own risk.\n")

	for _, cookie := range cm.jar.Cookies {
		if cookie.Name == "" {
			continue
		}

		domain := cookie.Domain
		includeSubdomains := false
		if strings.HasPrefix(domain, ".") {
			includeSubdomains = true
		}
		if cookie.HttpOnly {
			domain = httpOnlyPrefix + domain
		}

		path := cookie.Path
		if path == "" {
			path = "/"
		}

		secure := "FALSE"
		if cookie.Secure {
			secure = "TRUE"
		}

		includeSubdomainsText := "FALSE"
		if includeSubdomains {
			includeSubdomainsText = "TRUE"
		}

		expires := "0"
		if !cookie.Expires.IsZero() {
			expires = strconv.FormatInt(cookie.Expires.Unix(), 10)
		}

		builder.WriteString(strings.Join([]string{
			domain,
			includeSubdomainsText,
			path,
			secure,
			expires,
			cookie.Name,
			cookie.Value,
		}, "\t"))
		builder.WriteString("\n")
	}

	err := os.WriteFile(filepath, []byte(builder.String()), 0600)
	if err != nil {
		return fmt.Errorf("write cookie file failed: %v", err)
	}

	return nil
}

// AddCookie 添加Cookie
func (cm *CookieManager) AddCookie(cookie *CookieEntry) {
	if cookie == nil {
		return
	}

	// 查找是否已存在相同的Cookie（相同name、domain、path）
	for i, existingCookie := range cm.jar.Cookies {
		if existingCookie.Name == cookie.Name &&
			existingCookie.Domain == cookie.Domain &&
			existingCookie.Path == cookie.Path {
			// 更新现有Cookie
			cm.jar.Cookies[i] = *cookie
			return
		}
	}

	// 添加新Cookie
	cm.jar.Cookies = append(cm.jar.Cookies, *cookie)
}

// GetCookiesForURL 获取指定URL适用的Cookie
func (cm *CookieManager) GetCookiesForURL(urlStr string) []*CookieEntry {
	u, err := url.Parse(urlStr)
	if err != nil {
		return nil
	}

	var result []*CookieEntry
	for i, cookie := range cm.jar.Cookies {
		if cm.isCookieApplicable(&cookie, u) {
			result = append(result, &cm.jar.Cookies[i])
		}
	}

	return result
}

// isCookieApplicable 检查Cookie是否适用于指定URL
func (cm *CookieManager) isCookieApplicable(cookie *CookieEntry, u *url.URL) bool {
	// 检查过期时间
	if !cookie.Expires.IsZero() && cookie.Expires.Before(time.Now()) {
		return false
	}

	// 检查域名匹配
	if !cm.domainMatches(cookie.Domain, u.Host) {
		return false
	}

	// 检查路径匹配
	if !cm.pathMatches(cookie.Path, u.Path) {
		return false
	}

	// 检查HTTPS限制
	if cookie.Secure && u.Scheme != "https" {
		return false
	}

	return true
}

// domainMatches 检查域名是否匹配
func (cm *CookieManager) domainMatches(cookieDomain, host string) bool {
	if cookieDomain == "" {
		return true
	}

	// 完全匹配
	if cookieDomain == host {
		return true
	}

	// 域名匹配（支持子域名）
	if strings.HasPrefix(cookieDomain, ".") {
		return strings.HasSuffix(host, cookieDomain) || host == cookieDomain[1:]
	}

	return false
}

// pathMatches 检查路径是否匹配
func (cm *CookieManager) pathMatches(cookiePath, urlPath string) bool {
	if cookiePath == "" || cookiePath == "/" {
		return true
	}

	// 确保路径以/开头
	if !strings.HasPrefix(cookiePath, "/") {
		cookiePath = "/" + cookiePath
	}

	return strings.HasPrefix(urlPath, cookiePath)
}

// UpdateFromResponse 从HTTP响应更新Cookie
func (cm *CookieManager) UpdateFromResponse(resp *http.Response) {
	if resp == nil {
		return
	}

	cookies := resp.Cookies()
	for _, httpCookie := range cookies {
		cookie := &CookieEntry{
			Name:     httpCookie.Name,
			Value:    httpCookie.Value,
			Domain:   httpCookie.Domain,
			Path:     httpCookie.Path,
			Expires:  httpCookie.Expires,
			MaxAge:   httpCookie.MaxAge,
			Secure:   httpCookie.Secure,
			HttpOnly: httpCookie.HttpOnly,
		}

		// 处理SameSite属性
		switch httpCookie.SameSite {
		case http.SameSiteDefaultMode:
			cookie.SameSite = "Default"
		case http.SameSiteLaxMode:
			cookie.SameSite = "Lax"
		case http.SameSiteStrictMode:
			cookie.SameSite = "Strict"
		case http.SameSiteNoneMode:
			cookie.SameSite = "None"
		}

		// 如果没有设置域名，使用响应的Host
		if cookie.Domain == "" {
			if resp.Request != nil && resp.Request.URL != nil {
				cookie.Domain = resp.Request.URL.Host
			}
		}

		// 如果没有设置路径，使用默认路径
		if cookie.Path == "" {
			cookie.Path = "/"
		}

		cm.AddCookie(cookie)
	}
}

// CleanExpired 清理过期Cookie
func (cm *CookieManager) CleanExpired() {
	now := time.Now()

	// Pre-allocate slice with current capacity to reduce allocations
	validCookies := make([]CookieEntry, 0, len(cm.jar.Cookies))

	for _, cookie := range cm.jar.Cookies {
		// 检查是否过期
		if !cookie.Expires.IsZero() && cookie.Expires.Before(now) {
			continue // 跳过过期Cookie
		}

		validCookies = append(validCookies, cookie)
	}

	cm.jar.Cookies = validCookies
}

// ClearCookies 清除所有Cookie
func (cm *CookieManager) ClearCookies() {
	cm.jar.Cookies = make([]CookieEntry, 0)
}
